/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'chandan' at '8/23/16 9:17 AM' with Gradle 2.10
 *
 * @author chandan, @date 8/23/16 9:17 AM
 */



public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
